### ISSUE TITLE
Draft of register specification

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/harp.device.white-rabbit#1]
### Sends out periodic messages eg. 250hz (1 register for Event U32 counter, 1 Register for writing period/frequency)

e.g.:
```
 Timer:
    address: 33
    type: U32
    access: [Write, Event]
    description: Unitary counter that periodically produces a value at the frequency defined by register TimerFrequency.
  TimerFrequency:
    address: 34
    type: U8
    access: Write
    maskType: TimerRate
    description: Frequency at which the Timer will generate new values.
```

## IsConnected.
 U16 > each bit is a device/port connected(1) or not (0). Emit a message each time it changes.
eg.:
```
 DevicesConnected:
    address: 32
    type: U8
    access: Read
    maskType: ConnectedDevices
    description: Specifies which CLK_OUT ports have devices connected.
```
